# Global configuration file for the installation.
# Within this file mandatory and optional fields are defined.
application:
  name: "Land Matrix Knowledge Platform global edition"
  fields:
    mandatory:
      name:
        type: String
      area:
        type: Number
        validator: if(value >= 0){return true;} else {return "Must be greater than 0";}
      project_use:
        type: String
        predefined:
        - food production
        - tourism
        - forestry for wood and fiber
        - agrofuels
      project_status:
        type: String
        predefined:
        - pending
        - signed
        - abandoned
    optional:
      year_of_investment:
        type: Date
        validator: if(value == 0 || (value > 1900 && value < 2100)){return true;} else {return "1900 < year of investment < 2100";}
      Spatial uncertainty:
        type: String
