application:
  geometry:
    type: Polygon
    coordinates: [[[100.081,13.9099],[107.635,13.9099],[107.635,22.509],[100.081,22.509],[100.081,13.9099]]]
  name: ສາທາລະນະລັດປະຊາທິປະໄຕ ປະຊາຊົນລາວ
  layers:
  - name: "DECIDE Info Poverty"
    url: "http://www.decide.la/geoserver/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "decide:village-polygon"
    - transparent: true
    - styles: "vrppoac26"
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [11063487.59, 1543945.80, 12059351.76, 2593727.60]
    - opacity: 0.7